[2024-10-09 17:08:51,205] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_test manual__2024-10-09T17:08:48.300275+00:00 [queued]>
[2024-10-09 17:08:51,220] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_test manual__2024-10-09T17:08:48.300275+00:00 [queued]>
[2024-10-09 17:08:51,220] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 17:08:51,220] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-09 17:08:51,220] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 17:08:51,238] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_test> on 2024-10-09 17:08:48.300275+00:00
[2024-10-09 17:08:51,242] {standard_task_runner.py:52} INFO - Started process 378 to run task
[2024-10-09 17:08:51,245] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_test', 'manual__2024-10-09T17:08:48.300275+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpwwsi3xkh', '--error-file', '/tmp/tmpaf1i65uj']
[2024-10-09 17:08:51,246] {standard_task_runner.py:80} INFO - Job 4: Subtask dbt_test
[2024-10-09 17:08:51,313] {task_command.py:370} INFO - Running <TaskInstance: user_behaviour.dbt_test manual__2024-10-09T17:08:48.300275+00:00 [running]> on host acfcc9bdc161
[2024-10-09 17:08:51,404] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_behaviour
AIRFLOW_CTX_TASK_ID=dbt_test
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T17:08:48.300275+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T17:08:48.300275+00:00
[2024-10-09 17:08:51,405] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-09 17:08:51,406] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt test --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-09 17:08:51,415] {subprocess.py:85} INFO - Output:
[2024-10-09 17:08:54,042] {subprocess.py:92} INFO - Running with dbt=1.0.0-b2
[2024-10-09 17:08:57,648] {subprocess.py:92} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-09 17:08:57,648] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2024-10-09 17:08:57,648] {subprocess.py:92} INFO - - models.data_pipeline.marts
[2024-10-09 17:08:57,648] {subprocess.py:92} INFO - 
[2024-10-09 17:08:57,663] {subprocess.py:92} INFO - Found 2 models, 3 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
[2024-10-09 17:08:57,664] {subprocess.py:92} INFO - 
[2024-10-09 17:08:59,561] {subprocess.py:92} INFO - 17:08:59 | Concurrency: 10 threads (target='dev')
[2024-10-09 17:08:59,561] {subprocess.py:92} INFO - 17:08:59 |
[2024-10-09 17:08:59,570] {subprocess.py:92} INFO - 17:08:59 | 1 of 3 START test source_not_null_tpch_orders_o_orderkey............. [RUN]
[2024-10-09 17:08:59,571] {subprocess.py:92} INFO - 17:08:59 | 2 of 3 START test source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_ [RUN]
[2024-10-09 17:08:59,572] {subprocess.py:92} INFO - 17:08:59 | 3 of 3 START test source_unique_tpch_orders_o_orderkey............... [RUN]
[2024-10-09 17:09:00,726] {subprocess.py:92} INFO - 17:09:00 | 3 of 3 PASS source_unique_tpch_orders_o_orderkey..................... [[32mPASS[0m in 1.15s]
[2024-10-09 17:09:01,825] {subprocess.py:92} INFO - 17:09:01 | 1 of 3 PASS source_not_null_tpch_orders_o_orderkey................... [[32mPASS[0m in 2.26s]
[2024-10-09 17:09:01,887] {subprocess.py:92} INFO - 17:09:01 | 2 of 3 PASS source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_ [[32mPASS[0m in 2.32s]
[2024-10-09 17:09:01,986] {subprocess.py:92} INFO - 17:09:01 |
[2024-10-09 17:09:01,986] {subprocess.py:92} INFO - 17:09:01 | Finished running 3 tests in 4.32s.
[2024-10-09 17:09:01,996] {subprocess.py:92} INFO - 
[2024-10-09 17:09:01,996] {subprocess.py:92} INFO - [32mCompleted successfully[0m
[2024-10-09 17:09:01,996] {subprocess.py:92} INFO - 
[2024-10-09 17:09:01,996] {subprocess.py:92} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2024-10-09 17:09:03,219] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-09 17:09:03,265] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_test, execution_date=20241009T170848, start_date=20241009T170851, end_date=20241009T170903
[2024-10-09 17:09:03,301] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 17:09:03,344] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
