[2024-10-09 05:49:36,239] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_test manual__2024-10-09T05:49:33.187668+00:00 [queued]>
[2024-10-09 05:49:36,251] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_test manual__2024-10-09T05:49:33.187668+00:00 [queued]>
[2024-10-09 05:49:36,251] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 05:49:36,251] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-09 05:49:36,251] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 05:49:36,266] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_test> on 2024-10-09 05:49:33.187668+00:00
[2024-10-09 05:49:36,269] {standard_task_runner.py:52} INFO - Started process 119 to run task
[2024-10-09 05:49:36,272] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_test', 'manual__2024-10-09T05:49:33.187668+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmplvzgx47x', '--error-file', '/tmp/tmpacai5q7u']
[2024-10-09 05:49:36,273] {standard_task_runner.py:80} INFO - Job 4: Subtask dbt_test
[2024-10-09 05:49:36,327] {task_command.py:370} INFO - Running <TaskInstance: user_behaviour.dbt_test manual__2024-10-09T05:49:33.187668+00:00 [running]> on host 82b931b01445
[2024-10-09 05:49:36,401] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_behaviour
AIRFLOW_CTX_TASK_ID=dbt_test
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T05:49:33.187668+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T05:49:33.187668+00:00
[2024-10-09 05:49:36,401] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-09 05:49:36,402] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt test --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-09 05:49:36,410] {subprocess.py:85} INFO - Output:
[2024-10-09 05:49:38,972] {subprocess.py:92} INFO - Running with dbt=1.0.0-b2
[2024-10-09 05:49:42,197] {subprocess.py:92} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-09 05:49:42,197] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2024-10-09 05:49:42,197] {subprocess.py:92} INFO - - models.data_pipeline.marts
[2024-10-09 05:49:42,197] {subprocess.py:92} INFO - 
[2024-10-09 05:49:42,212] {subprocess.py:92} INFO - Found 2 models, 3 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
[2024-10-09 05:49:42,214] {subprocess.py:92} INFO - 
[2024-10-09 05:49:43,331] {subprocess.py:92} INFO - 05:49:43 | Concurrency: 10 threads (target='dev')
[2024-10-09 05:49:43,331] {subprocess.py:92} INFO - 05:49:43 |
[2024-10-09 05:49:43,337] {subprocess.py:92} INFO - 05:49:43 | 1 of 3 START test source_not_null_tpch_orders_o_orderkey............. [RUN]
[2024-10-09 05:49:43,340] {subprocess.py:92} INFO - 05:49:43 | 2 of 3 START test source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_ [RUN]
[2024-10-09 05:49:43,355] {subprocess.py:92} INFO - 05:49:43 | 3 of 3 START test source_unique_tpch_orders_o_orderkey............... [RUN]
[2024-10-09 05:49:44,931] {subprocess.py:92} INFO - 05:49:44 | 2 of 3 PASS source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_ [[32mPASS[0m in 1.59s]
[2024-10-09 05:49:45,083] {subprocess.py:92} INFO - 05:49:45 | 3 of 3 PASS source_unique_tpch_orders_o_orderkey..................... [[32mPASS[0m in 1.73s]
[2024-10-09 05:49:45,267] {subprocess.py:92} INFO - 05:49:45 | 1 of 3 PASS source_not_null_tpch_orders_o_orderkey................... [[32mPASS[0m in 1.93s]
[2024-10-09 05:49:45,348] {subprocess.py:92} INFO - 05:49:45 |
[2024-10-09 05:49:45,348] {subprocess.py:92} INFO - 05:49:45 | Finished running 3 tests in 3.13s.
[2024-10-09 05:49:45,356] {subprocess.py:92} INFO - 
[2024-10-09 05:49:45,356] {subprocess.py:92} INFO - [32mCompleted successfully[0m
[2024-10-09 05:49:45,357] {subprocess.py:92} INFO - 
[2024-10-09 05:49:45,357] {subprocess.py:92} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2024-10-09 05:49:46,507] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-09 05:49:46,541] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_test, execution_date=20241009T054933, start_date=20241009T054936, end_date=20241009T054946
[2024-10-09 05:49:46,583] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 05:49:46,630] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
