[2024-10-09 17:20:30,149] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T17:16:14.125988+00:00 [queued]>
[2024-10-09 17:20:30,163] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T17:16:14.125988+00:00 [queued]>
[2024-10-09 17:20:30,164] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 17:20:30,164] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-09 17:20:30,164] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 17:20:30,182] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2024-10-09 17:16:14.125988+00:00
[2024-10-09 17:20:30,188] {standard_task_runner.py:52} INFO - Started process 1031 to run task
[2024-10-09 17:20:30,193] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_run', 'manual__2024-10-09T17:16:14.125988+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmp20itrs1u', '--error-file', '/tmp/tmpp8xc9mvt']
[2024-10-09 17:20:30,193] {standard_task_runner.py:80} INFO - Job 14: Subtask dbt_run
[2024-10-09 17:20:30,255] {task_command.py:370} INFO - Running <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T17:16:14.125988+00:00 [running]> on host acfcc9bdc161
[2024-10-09 17:20:30,335] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_behaviour
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T17:16:14.125988+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T17:16:14.125988+00:00
[2024-10-09 17:20:30,336] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-09 17:20:30,337] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-09 17:20:30,347] {subprocess.py:85} INFO - Output:
[2024-10-09 17:20:32,352] {subprocess.py:92} INFO - Running with dbt=1.0.0-b2
[2024-10-09 17:20:33,653] {subprocess.py:92} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-09 17:20:33,653] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2024-10-09 17:20:33,653] {subprocess.py:92} INFO - - models.data_pipeline.marts
[2024-10-09 17:20:33,653] {subprocess.py:92} INFO - 
[2024-10-09 17:20:33,730] {subprocess.py:92} INFO - Found 2 models, 3 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
[2024-10-09 17:20:33,732] {subprocess.py:92} INFO - 
[2024-10-09 17:20:34,962] {subprocess.py:92} INFO - 17:20:34 | Concurrency: 10 threads (target='dev')
[2024-10-09 17:20:34,962] {subprocess.py:92} INFO - 17:20:34 |
[2024-10-09 17:20:34,968] {subprocess.py:92} INFO - 17:20:34 | 1 of 1 START view model dbt_schema.stg_tpch_orders................... [RUN]
[2024-10-09 17:20:35,614] {subprocess.py:92} INFO - 17:20:35 | 1 of 1 OK created view model dbt_schema.stg_tpch_orders.............. [[32mSUCCESS 1[0m in 0.65s]
[2024-10-09 17:20:35,671] {subprocess.py:92} INFO - 17:20:35 |
[2024-10-09 17:20:35,671] {subprocess.py:92} INFO - 17:20:35 | Finished running 1 view model in 1.94s.
[2024-10-09 17:20:35,677] {subprocess.py:92} INFO - 
[2024-10-09 17:20:35,678] {subprocess.py:92} INFO - [32mCompleted successfully[0m
[2024-10-09 17:20:35,678] {subprocess.py:92} INFO - 
[2024-10-09 17:20:35,678] {subprocess.py:92} INFO - Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-10-09 17:20:36,799] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-09 17:20:36,830] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_run, execution_date=20241009T171614, start_date=20241009T172030, end_date=20241009T172036
[2024-10-09 17:20:36,874] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 17:20:36,907] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
