[2024-10-09 05:50:27,004] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_test scheduled__2024-10-08T00:00:00+00:00 [queued]>
[2024-10-09 05:50:27,016] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_test scheduled__2024-10-08T00:00:00+00:00 [queued]>
[2024-10-09 05:50:27,017] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 05:50:27,017] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-09 05:50:27,017] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 05:50:27,032] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_test> on 2024-10-08 00:00:00+00:00
[2024-10-09 05:50:27,035] {standard_task_runner.py:52} INFO - Started process 313 to run task
[2024-10-09 05:50:27,038] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_test', 'scheduled__2024-10-08T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpzn5ppq67', '--error-file', '/tmp/tmpsazrlfe4']
[2024-10-09 05:50:27,039] {standard_task_runner.py:80} INFO - Job 10: Subtask dbt_test
[2024-10-09 05:50:27,093] {task_command.py:370} INFO - Running <TaskInstance: user_behaviour.dbt_test scheduled__2024-10-08T00:00:00+00:00 [running]> on host 82b931b01445
[2024-10-09 05:50:27,165] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_behaviour
AIRFLOW_CTX_TASK_ID=dbt_test
AIRFLOW_CTX_EXECUTION_DATE=2024-10-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-08T00:00:00+00:00
[2024-10-09 05:50:27,166] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-09 05:50:27,166] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt test --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-09 05:50:27,174] {subprocess.py:85} INFO - Output:
[2024-10-09 05:50:28,349] {subprocess.py:92} INFO - Running with dbt=1.0.0-b2
[2024-10-09 05:50:29,543] {subprocess.py:92} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-09 05:50:29,543] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2024-10-09 05:50:29,543] {subprocess.py:92} INFO - - models.data_pipeline.marts
[2024-10-09 05:50:29,543] {subprocess.py:92} INFO - 
[2024-10-09 05:50:29,613] {subprocess.py:92} INFO - Found 2 models, 3 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
[2024-10-09 05:50:29,615] {subprocess.py:92} INFO - 
[2024-10-09 05:50:30,611] {subprocess.py:92} INFO - 05:50:30 | Concurrency: 10 threads (target='dev')
[2024-10-09 05:50:30,611] {subprocess.py:92} INFO - 05:50:30 |
[2024-10-09 05:50:30,620] {subprocess.py:92} INFO - 05:50:30 | 1 of 3 START test source_not_null_tpch_orders_o_orderkey............. [RUN]
[2024-10-09 05:50:30,621] {subprocess.py:92} INFO - 05:50:30 | 2 of 3 START test source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_ [RUN]
[2024-10-09 05:50:30,623] {subprocess.py:92} INFO - 05:50:30 | 3 of 3 START test source_unique_tpch_orders_o_orderkey............... [RUN]
[2024-10-09 05:50:32,293] {subprocess.py:92} INFO - 05:50:32 | 1 of 3 PASS source_not_null_tpch_orders_o_orderkey................... [[32mPASS[0m in 1.67s]
[2024-10-09 05:50:32,450] {subprocess.py:92} INFO - 05:50:32 | 3 of 3 PASS source_unique_tpch_orders_o_orderkey..................... [[32mPASS[0m in 1.83s]
[2024-10-09 05:50:32,732] {subprocess.py:92} INFO - 05:50:32 | 2 of 3 PASS source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_ [[32mPASS[0m in 2.11s]
[2024-10-09 05:50:32,809] {subprocess.py:92} INFO - 05:50:32 |
[2024-10-09 05:50:32,810] {subprocess.py:92} INFO - 05:50:32 | Finished running 3 tests in 3.19s.
[2024-10-09 05:50:32,817] {subprocess.py:92} INFO - 
[2024-10-09 05:50:32,817] {subprocess.py:92} INFO - [32mCompleted successfully[0m
[2024-10-09 05:50:32,817] {subprocess.py:92} INFO - 
[2024-10-09 05:50:32,817] {subprocess.py:92} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2024-10-09 05:50:33,944] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-09 05:50:33,985] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_test, execution_date=20241008T000000, start_date=20241009T055027, end_date=20241009T055033
[2024-10-09 05:50:34,022] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 05:50:34,066] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
