[2024-10-09 03:10:45,612] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T03:10:34.485201+00:00 [queued]>
[2024-10-09 03:10:45,626] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T03:10:34.485201+00:00 [queued]>
[2024-10-09 03:10:45,627] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 03:10:45,627] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-09 03:10:45,627] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 03:10:45,642] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2024-10-09 03:10:34.485201+00:00
[2024-10-09 03:10:45,646] {standard_task_runner.py:52} INFO - Started process 178 to run task
[2024-10-09 03:10:45,649] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_run', 'manual__2024-10-09T03:10:34.485201+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpmpqcfk8w', '--error-file', '/tmp/tmpgs2n1vsb']
[2024-10-09 03:10:45,649] {standard_task_runner.py:80} INFO - Job 4: Subtask dbt_run
[2024-10-09 03:10:45,706] {task_command.py:370} INFO - Running <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T03:10:34.485201+00:00 [running]> on host 33db15a69f99
[2024-10-09 03:10:45,786] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_behaviour
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T03:10:34.485201+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T03:10:34.485201+00:00
[2024-10-09 03:10:45,787] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-09 03:10:45,787] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-09 03:10:45,795] {subprocess.py:85} INFO - Output:
[2024-10-09 03:10:48,216] {subprocess.py:92} INFO - Running with dbt=1.0.0-b2
[2024-10-09 03:10:49,424] {subprocess.py:92} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-09 03:10:49,424] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2024-10-09 03:10:49,425] {subprocess.py:92} INFO - - models.data_pipeline.marts
[2024-10-09 03:10:49,425] {subprocess.py:92} INFO - 
[2024-10-09 03:10:49,489] {subprocess.py:92} INFO - Found 2 models, 3 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
[2024-10-09 03:10:49,490] {subprocess.py:92} INFO - 
[2024-10-09 03:10:50,978] {subprocess.py:92} INFO - 03:10:50 | Concurrency: 10 threads (target='dev')
[2024-10-09 03:10:50,979] {subprocess.py:92} INFO - 03:10:50 |
[2024-10-09 03:10:50,984] {subprocess.py:92} INFO - 03:10:50 | 1 of 1 START view model dbt_schema.stg_tpch_orders................... [RUN]
[2024-10-09 03:10:52,234] {subprocess.py:92} INFO - 03:10:52 | 1 of 1 OK created view model dbt_schema.stg_tpch_orders.............. [[32mSUCCESS 1[0m in 1.25s]
[2024-10-09 03:10:52,300] {subprocess.py:92} INFO - 03:10:52 |
[2024-10-09 03:10:52,301] {subprocess.py:92} INFO - 03:10:52 | Finished running 1 view model in 2.81s.
[2024-10-09 03:10:52,309] {subprocess.py:92} INFO - 
[2024-10-09 03:10:52,309] {subprocess.py:92} INFO - [32mCompleted successfully[0m
[2024-10-09 03:10:52,309] {subprocess.py:92} INFO - 
[2024-10-09 03:10:52,309] {subprocess.py:92} INFO - Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-10-09 03:10:52,560] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-09 03:10:52,600] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_run, execution_date=20241009T031034, start_date=20241009T031045, end_date=20241009T031052
[2024-10-09 03:10:52,616] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 03:10:52,649] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
