[2024-10-09 05:49:47,475] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T05:49:33.187668+00:00 [queued]>
[2024-10-09 05:49:47,486] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T05:49:33.187668+00:00 [queued]>
[2024-10-09 05:49:47,487] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 05:49:47,487] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-10-09 05:49:47,487] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-10-09 05:49:47,501] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2024-10-09 05:49:33.187668+00:00
[2024-10-09 05:49:47,504] {standard_task_runner.py:52} INFO - Started process 175 to run task
[2024-10-09 05:49:47,507] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_run', 'manual__2024-10-09T05:49:33.187668+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmp4drirhck', '--error-file', '/tmp/tmp12t9vjjq']
[2024-10-09 05:49:47,508] {standard_task_runner.py:80} INFO - Job 5: Subtask dbt_run
[2024-10-09 05:49:47,558] {task_command.py:370} INFO - Running <TaskInstance: user_behaviour.dbt_run manual__2024-10-09T05:49:33.187668+00:00 [running]> on host 82b931b01445
[2024-10-09 05:49:47,629] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_behaviour
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T05:49:33.187668+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T05:49:33.187668+00:00
[2024-10-09 05:49:47,630] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-10-09 05:49:47,631] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-09 05:49:47,639] {subprocess.py:85} INFO - Output:
[2024-10-09 05:49:50,327] {subprocess.py:92} INFO - Running with dbt=1.0.0-b2
[2024-10-09 05:49:51,551] {subprocess.py:92} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-09 05:49:51,551] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2024-10-09 05:49:51,551] {subprocess.py:92} INFO - - models.data_pipeline.marts
[2024-10-09 05:49:51,551] {subprocess.py:92} INFO - 
[2024-10-09 05:49:51,621] {subprocess.py:92} INFO - Found 2 models, 3 tests, 0 snapshots, 0 analyses, 172 macros, 0 operations, 0 seed files, 2 sources, 0 exposures
[2024-10-09 05:49:51,623] {subprocess.py:92} INFO - 
[2024-10-09 05:49:53,339] {subprocess.py:92} INFO - 05:49:53 | Concurrency: 10 threads (target='dev')
[2024-10-09 05:49:53,339] {subprocess.py:92} INFO - 05:49:53 |
[2024-10-09 05:49:53,348] {subprocess.py:92} INFO - 05:49:53 | 1 of 1 START view model dbt_schema.stg_tpch_orders................... [RUN]
[2024-10-09 05:49:54,547] {subprocess.py:92} INFO - 05:49:54 | 1 of 1 OK created view model dbt_schema.stg_tpch_orders.............. [[32mSUCCESS 1[0m in 1.20s]
[2024-10-09 05:49:54,577] {subprocess.py:92} INFO - 05:49:54 |
[2024-10-09 05:49:54,577] {subprocess.py:92} INFO - 05:49:54 | Finished running 1 view model in 2.95s.
[2024-10-09 05:49:54,584] {subprocess.py:92} INFO - 
[2024-10-09 05:49:54,585] {subprocess.py:92} INFO - [32mCompleted successfully[0m
[2024-10-09 05:49:54,585] {subprocess.py:92} INFO - 
[2024-10-09 05:49:54,585] {subprocess.py:92} INFO - Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-10-09 05:49:55,730] {subprocess.py:96} INFO - Command exited with return code 0
[2024-10-09 05:49:55,762] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_run, execution_date=20241009T054933, start_date=20241009T054947, end_date=20241009T054955
[2024-10-09 05:49:55,781] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-09 05:49:55,812] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
